// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/dhtpb/dht.proto

package dhtpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_OP_UNKNOWN     Op = 0
	Op_OP_STORE       Op = 1
	Op_OP_FIND        Op = 2
	Op_OP_STORE_INDEX Op = 3
	Op_OP_FIND_INDEX  Op = 4
	Op_OP_PING        Op = 5
	Op_OP_CONNECT     Op = 6
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_STORE",
		2: "OP_FIND",
		3: "OP_STORE_INDEX",
		4: "OP_FIND_INDEX",
		5: "OP_PING",
		6: "OP_CONNECT",
	}
	Op_value = map[string]int32{
		"OP_UNKNOWN":     0,
		"OP_STORE":       1,
		"OP_FIND":        2,
		"OP_STORE_INDEX": 3,
		"OP_FIND_INDEX":  4,
		"OP_PING":        5,
		"OP_CONNECT":     6,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dhtpb_dht_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_proto_dhtpb_dht_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=dhtpb.Op" json:"op,omitempty"`
	ReqId         uint64                 `protobuf:"varint,2,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	IsResponse    bool                   `protobuf:"varint,3,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	FromId        []byte                 `protobuf:"bytes,5,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNKNOWN
}

func (x *Envelope) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *Envelope) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetFromId() []byte {
	if x != nil {
		return x.FromId
	}
	return nil
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs         int64                  `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	Replicas      []string               `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoreRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *StoreRequest) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{2}
}

func (x *StoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{3}
}

func (x *FindRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{4}
}

func (x *FindResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FindResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FindResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type IndexEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Meta          []byte                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	UpdatedUnix   int64                  `protobuf:"varint,4,opt,name=updated_unix,json=updatedUnix,proto3" json:"updated_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{5}
}

func (x *IndexEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IndexEntry) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *IndexEntry) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IndexEntry) GetUpdatedUnix() int64 {
	if x != nil {
		return x.UpdatedUnix
	}
	return 0
}

type StoreIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Entry         *IndexEntry            `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	TtlMs         int64                  `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	Replicas      []string               `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreIndexRequest) Reset() {
	*x = StoreIndexRequest{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIndexRequest) ProtoMessage() {}

func (x *StoreIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIndexRequest.ProtoReflect.Descriptor instead.
func (*StoreIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{6}
}

func (x *StoreIndexRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreIndexRequest) GetEntry() *IndexEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StoreIndexRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *StoreIndexRequest) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type StoreIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreIndexResponse) Reset() {
	*x = StoreIndexResponse{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIndexResponse) ProtoMessage() {}

func (x *StoreIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIndexResponse.ProtoReflect.Descriptor instead.
func (*StoreIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{7}
}

func (x *StoreIndexResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreIndexResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type FindIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindIndexRequest) Reset() {
	*x = FindIndexRequest{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindIndexRequest) ProtoMessage() {}

func (x *FindIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindIndexRequest.ProtoReflect.Descriptor instead.
func (*FindIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{8}
}

func (x *FindIndexRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FindIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Entries       []*IndexEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindIndexResponse) Reset() {
	*x = FindIndexResponse{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindIndexResponse) ProtoMessage() {}

func (x *FindIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindIndexResponse.ProtoReflect.Descriptor instead.
func (*FindIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{9}
}

func (x *FindIndexResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FindIndexResponse) GetEntries() []*IndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FindIndexResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectRequest) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *ConnectRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_dhtpb_dht_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhtpb_dht_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhtpb_dht_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *ConnectResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_proto_dhtpb_dht_proto protoreflect.FileDescriptor

const file_proto_dhtpb_dht_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dhtpb/dht.proto\x12\x05dhtpb\"\x90\x01\n" +
	"\bEnvelope\x12\x19\n" +
	"\x02op\x18\x01 \x01(\x0e2\t.dhtpb.OpR\x02op\x12\x15\n" +
	"\x06req_id\x18\x02 \x01(\x04R\x05reqId\x12\x1f\n" +
	"\vis_response\x18\x03 \x01(\bR\n" +
	"isResponse\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x17\n" +
	"\afrom_id\x18\x05 \x01(\fR\x06fromId\"i\n" +
	"\fStoreRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\x12\x1a\n" +
	"\breplicas\x18\x04 \x03(\tR\breplicas\"1\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"\x1f\n" +
	"\vFindRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"F\n" +
	"\fFindResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"s\n" +
	"\n" +
	"IndexEntry\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\fR\x04meta\x12!\n" +
	"\fupdated_unix\x18\x04 \x01(\x03R\vupdatedUnix\"\x81\x01\n" +
	"\x11StoreIndexRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05entry\x18\x02 \x01(\v2\x11.dhtpb.IndexEntryR\x05entry\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\x12\x1a\n" +
	"\breplicas\x18\x04 \x03(\tR\breplicas\"6\n" +
	"\x12StoreIndexResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"$\n" +
	"\x10FindIndexRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"b\n" +
	"\x11FindIndexResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.dhtpb.IndexEntryR\aentries\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"=\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"L\n" +
	"\x0fConnectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err*s\n" +
	"\x02Op\x12\x0e\n" +
	"\n" +
	"OP_UNKNOWN\x10\x00\x12\f\n" +
	"\bOP_STORE\x10\x01\x12\v\n" +
	"\aOP_FIND\x10\x02\x12\x12\n" +
	"\x0eOP_STORE_INDEX\x10\x03\x12\x11\n" +
	"\rOP_FIND_INDEX\x10\x04\x12\v\n" +
	"\aOP_PING\x10\x05\x12\x0e\n" +
	"\n" +
	"OP_CONNECT\x10\x06B6Z4github.com/SharefulNetworks/shareful-dht/proto/dhtpbb\x06proto3"

var (
	file_proto_dhtpb_dht_proto_rawDescOnce sync.Once
	file_proto_dhtpb_dht_proto_rawDescData []byte
)

func file_proto_dhtpb_dht_proto_rawDescGZIP() []byte {
	file_proto_dhtpb_dht_proto_rawDescOnce.Do(func() {
		file_proto_dhtpb_dht_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dhtpb_dht_proto_rawDesc), len(file_proto_dhtpb_dht_proto_rawDesc)))
	})
	return file_proto_dhtpb_dht_proto_rawDescData
}

var file_proto_dhtpb_dht_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dhtpb_dht_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_dhtpb_dht_proto_goTypes = []any{
	(Op)(0),                    // 0: dhtpb.Op
	(*Envelope)(nil),           // 1: dhtpb.Envelope
	(*StoreRequest)(nil),       // 2: dhtpb.StoreRequest
	(*StoreResponse)(nil),      // 3: dhtpb.StoreResponse
	(*FindRequest)(nil),        // 4: dhtpb.FindRequest
	(*FindResponse)(nil),       // 5: dhtpb.FindResponse
	(*IndexEntry)(nil),         // 6: dhtpb.IndexEntry
	(*StoreIndexRequest)(nil),  // 7: dhtpb.StoreIndexRequest
	(*StoreIndexResponse)(nil), // 8: dhtpb.StoreIndexResponse
	(*FindIndexRequest)(nil),   // 9: dhtpb.FindIndexRequest
	(*FindIndexResponse)(nil),  // 10: dhtpb.FindIndexResponse
	(*ConnectRequest)(nil),     // 11: dhtpb.ConnectRequest
	(*ConnectResponse)(nil),    // 12: dhtpb.ConnectResponse
}
var file_proto_dhtpb_dht_proto_depIdxs = []int32{
	0, // 0: dhtpb.Envelope.op:type_name -> dhtpb.Op
	6, // 1: dhtpb.StoreIndexRequest.entry:type_name -> dhtpb.IndexEntry
	6, // 2: dhtpb.FindIndexResponse.entries:type_name -> dhtpb.IndexEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_dhtpb_dht_proto_init() }
func file_proto_dhtpb_dht_proto_init() {
	if File_proto_dhtpb_dht_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dhtpb_dht_proto_rawDesc), len(file_proto_dhtpb_dht_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dhtpb_dht_proto_goTypes,
		DependencyIndexes: file_proto_dhtpb_dht_proto_depIdxs,
		EnumInfos:         file_proto_dhtpb_dht_proto_enumTypes,
		MessageInfos:      file_proto_dhtpb_dht_proto_msgTypes,
	}.Build()
	File_proto_dhtpb_dht_proto = out.File
	file_proto_dhtpb_dht_proto_goTypes = nil
	file_proto_dhtpb_dht_proto_depIdxs = nil
}
